// The pure half of the vendoring: what to fetch, and the assertion that the
// plugin still covers every check common-checks runs. No network, no disk.

export const UPSTREAM_REPO = "wow-look-at-my/actions";

/** The branch to vendor from. Overridable so a branch can be built before it merges. */
export function upstreamRef(env: NodeJS.ProcessEnv = process.env): string {
  return env.COMMON_CHECKS_REF || "master";
}

export interface CheckPlan {
  /** The action directory, which is also its `uses:` slug. */
  name: string;
  /**
   * Paths under the action directory to vendor. Empty when the check is not a
   * diagnostic source, in which case `why` says so.
   */
  files: string[];
  /** Why this entry contributes no diagnostics. Present only when files is empty. */
  why?: string;
}

// One entry per step common-checks runs. A step with no files is an explicit
// statement that nothing in an open file can violate it -- never an omission,
// because the assertion below cannot tell an omission from a decision.
export const PLAN: CheckPlan[] = [
  {
    name: "run-once",
    files: [],
    why: "it claims the workflow run for one job. There is no rule a file can break.",
  },
  { name: "no-all-builds-job", files: ["src/detect.ts"] },
  { name: "yaml-comment-block", files: ["src/scan.ts"] },
  { name: "no-tests-in-yaml", files: ["src/scan.ts"] },
  { name: "push-excludes-tags", files: ["src/scan.ts"] },
  {
    name: "ste-lint",
    files: ["src/lint.ts", "src/blocks.ts", "src/ste100-banned-words.ts", "src/guard.ts"],
  },
];

/**
 * Every action this repository's own common-checks composite runs, in the order
 * it runs them. Read with a regex rather than a YAML walk, matching how the
 * checks themselves read `uses:`: the key means the same thing at every depth.
 */
export function parseCheckSet(actionYml: string): string[] {
  const slugs: string[] = [];
  for (const line of actionYml.split(/\r?\n/)) {
    const match = /^\s*(?:-\s+)?uses:\s*(?:'([^']*)'|"([^"]*)"|(\S+))/.exec(line);
    if (!match) continue;
    const value = match[1] ?? match[2] ?? match[3] ?? "";
    // `owner/repo@slug#ref` is this org's action-reference spelling.
    const ref = new RegExp(`^${UPSTREAM_REPO}@([A-Za-z0-9._-]+)#`).exec(value);
    if (ref) slugs.push(ref[1]);
  }
  return slugs;
}

/**
 * Fails when the plugin's plan and the composite's step list have drifted.
 * This is the whole sync guarantee: adding a check to common-checks turns this
 * build red until the plugin either covers it or states why it cannot.
 */
export function assertPlanCoversCheckSet(plan: CheckPlan[], checkSet: string[]): void {
  const planned = new Set(plan.map((entry) => entry.name));
  const upstream = new Set(checkSet);

  const missing = [...upstream].filter((name) => !planned.has(name)).sort();
  const stale = [...planned].filter((name) => !upstream.has(name)).sort();
  if (missing.length === 0 && stale.length === 0) return;

  const problems: string[] = [];
  if (missing.length > 0) {
    problems.push(
      `common-checks now runs ${missing.join(", ")}, which this plugin does not cover. ` +
        "Add an entry to PLAN naming the module to vendor, write the adapter that turns its " +
        "findings into diagnostics, or add the entry with no files and say why nothing in an " +
        "open file can violate it.",
    );
  }
  if (stale.length > 0) {
    problems.push(
      `PLAN still names ${stale.join(", ")}, which common-checks no longer runs. ` +
        "Drop the entry, its vendored files and its adapter.",
    );
  }
  throw new Error(`the plugin and common-checks have drifted:\n  ${problems.join("\n  ")}`);
}

/**
 * The provenance header. The body below it is the upstream file byte for byte,
 * so a diff against upstream shows only this block.
 */
export function stampHeader(commit: string, path: string, body: string): string {
  const source = `https://github.com/${UPSTREAM_REPO}/blob/${commit}/${path}`;
  return (
    `// Vendored from ${UPSTREAM_REPO} at ${commit}\n` +
    `// Source: ${source}\n` +
    "// Generated by .github/scripts/vendor-common-checks. Do not edit: a build overwrites it.\n" +
    "\n" +
    body
  );
}

/** Where a vendored upstream path lands inside the plugin. */
export function vendorPath(check: string, path: string): string {
  return `${check}/${path.replace(/^src\//, "")}`;
}

export function notice(commit: string, plan: CheckPlan[]): string {
  const covered = plan.filter((entry) => entry.files.length > 0);
  const uncovered = plan.filter((entry) => entry.files.length === 0);
  const lines = [
    "# Vendored check modules",
    "",
    `Fetched from [${UPSTREAM_REPO}](https://github.com/${UPSTREAM_REPO}) at commit \`${commit}\`.`,
    "",
    "Every file here is generated. Edit the check upstream, not this copy: the",
    "plugin's build re-fetches these on every run and overwrites any local change.",
    "",
    "## Covered",
    "",
    ...covered.map((entry) => `- \`${entry.name}\` -- ${entry.files.join(", ")}`),
    "",
    "## Runs in common-checks, reports nothing here",
    "",
    ...uncovered.map((entry) => `- \`${entry.name}\` -- ${entry.why}`),
    "",
  ];
  return lines.join("\n");
}
