name: Setup marketplace-build
description: Build or restore cached marketplace-build CLI

runs:
  using: composite
  steps:
    - name: Fetch tags
      shell: bash
      run: git fetch --tags --force

    - uses: extractions/setup-just@v2
    
    - uses: wow-look-at-my/go-toolchain@latest
      with:
        working-directory: "tools/marketplace-build"

    - run: cp "tools/marketplace-build/build/marketplace-build" "/usr/local/bin/marketplace-build"
      shell: bash
      
