// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `\b[A-Za-z][A-Za-z0-9]*(?:_[A-Za-z0-9]+)+\b|\b[a-z][a-z0-9]*[A-Z][A-Za-z0-9]*\b|\b[A-Z][a-z0-9]+[A-Z][A-Za-z0-9]*\b`

package main


import "github.com/wow-look-at-my/go-regex-compiler/match"



// matchesIdentifierShape reports whether input fully matches the regex `\b[A-Za-z][A-Za-z0-9]*(?:_[A-Za-z0-9]+)+\b|\b[a-z][a-z0-9]*[A-Z][A-Za-z0-9]*\b|\b[A-Z][a-z0-9]+[A-Z][A-Za-z0-9]*\b`.
func matchesIdentifierShape(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {

		case 0:
			switch {
			case match.InRange(c, 'A', 'Z'): state = 1
			case match.InRange(c, 'a', 'z'): state = 2
			default: return false
			}
		case 1:
			switch {
			case match.InRange(c, '0', '9'): state = 3
			case match.InRange(c, 'A', 'Z'): state = 4
			case c == '_': state = 5
			case match.InRange(c, 'a', 'z'): state = 3
			default: return false
			}
		case 2:
			switch {
			case match.InRange(c, '0', '9'): state = 2
			case match.InRange(c, 'A', 'Z'): state = 6
			case c == '_': state = 5
			case match.InRange(c, 'a', 'z'): state = 2
			default: return false
			}
		case 3:
			switch {
			case match.InRange(c, '0', '9'): state = 3
			case match.InRange(c, 'A', 'Z'): state = 7
			case c == '_': state = 5
			case match.InRange(c, 'a', 'z'): state = 3
			default: return false
			}
		case 4:
			switch {
			case match.InRange(c, '0', '9'), match.InRange(c, 'A', 'Z'): state = 4
			case c == '_': state = 5
			case match.InRange(c, 'a', 'z'): state = 4
			default: return false
			}
		case 5:
			switch {
			case match.InRange(c, '0', '9'), match.InRange(c, 'A', 'Z'), match.InRange(c, 'a', 'z'): state = 8
			default: return false
			}
		case 6:
			switch {
			case match.InRange(c, '0', '9'), match.InRange(c, 'A', 'Z'): state = 6
			case c == '_': state = 5
			case match.InRange(c, 'a', 'z'): state = 6
			default: return false
			}
		case 7:
			switch {
			case match.InRange(c, '0', '9'), match.InRange(c, 'A', 'Z'): state = 7
			case c == '_': state = 5
			case match.InRange(c, 'a', 'z'): state = 7
			default: return false
			}
		case 8:
			switch {
			case match.InRange(c, '0', '9'), match.InRange(c, 'A', 'Z'): state = 8
			case c == '_': state = 5
			case match.InRange(c, 'a', 'z'): state = 8
			default: return false
			}
		default:
			return false
		}
	}

	switch state {
	case 6, 7, 8:
		return true
	default:
		return false
	}
}
