// Command vendor-docker-docs refreshes the Docker reference text that the
// `docs` plugin's dockerfile and docker-compose skills read from.
//
// The reference is vendored rather than summarized. A paraphrase of a
// specification is a second source of truth that goes stale with nothing to
// signal it; a verbatim copy pinned to a commit can be diffed against upstream
// and regenerated in one command.
//
// Usage: go run ./tools/vendor-docker-docs [-root <repo root>]
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

func main() {
	root := flag.String("root", ".", "repository root to write into")
	flag.Parse()

	if err := run(*root); err != nil {
		fmt.Fprintln(os.Stderr, "vendor-docker-docs:", err)
		os.Exit(1)
	}
}

func run(root string) error {
	// One commit per upstream, resolved once, so every file in a run comes
	// from the same tree.
	commits := map[string]string{}
	fetchers := map[string]*fetcher{}

	for _, b := range bundles {
		for _, p := range b.Pages {
			if _, done := commits[p.Src.Repo]; done {
				continue
			}
			commit, err := resolve(p.Src)
			if err != nil {
				return err
			}
			commits[p.Src.Repo] = commit
			fetchers[p.Src.Repo] = newFetcher(p.Src.Repo, commit)
			fmt.Printf("%s@%s -> %s\n", p.Src.Repo, p.Src.Ref, commit)
		}
	}

	for _, b := range bundles {
		dir := filepath.Join(root, "plugins", "docs", "skills", b.Skill, "reference")
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
		if err := writeBundle(dir, b, commits, fetchers); err != nil {
			return err
		}
	}
	return nil
}

func writeBundle(dir string, b bundle, commits map[string]string, fetchers map[string]*fetcher) error {
	written := map[string]bool{}

	for _, p := range b.Pages {
		f := fetchers[p.Src.Repo]
		raw, err := f.get(p.Path)
		if err != nil {
			return err
		}
		out, err := render(raw, p, commits[p.Src.Repo], f.get)
		if err != nil {
			return fmt.Errorf("%s: %w", p.Path, err)
		}
		if err := os.WriteFile(filepath.Join(dir, p.Out), []byte(out), 0o644); err != nil {
			return err
		}
		written[p.Out] = true
		fmt.Printf("  %s/%s (%d bytes)\n", b.Skill, p.Out, len(out))
	}

	// A file left behind after its page is dropped from the plan reads as
	// current reference and is not regenerated by anything.
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		name := e.Name()
		if name == noticeFile || written[name] {
			continue
		}
		if err := os.Remove(filepath.Join(dir, name)); err != nil {
			return err
		}
		fmt.Printf("  %s/%s removed (no longer in the plan)\n", b.Skill, name)
	}

	return os.WriteFile(filepath.Join(dir, noticeFile), []byte(notice(b, commits)), 0o644)
}

const noticeFile = "NOTICE.md"

func notice(b bundle, commits map[string]string) string {
	var s strings.Builder
	s.WriteString("# Vendored reference\n\n")
	s.WriteString("Generated by `go run ./tools/vendor-docker-docs`. Do not edit these files by hand -- ")
	s.WriteString("a regenerate overwrites them.\n\n")
	fmt.Fprintf(&s, "Last regenerated %s.\n\n", time.Now().UTC().Format("2006-01-02"))

	seen := map[string]upstream{}
	for _, p := range b.Pages {
		seen[p.Src.Repo] = p.Src
	}
	repos := make([]string, 0, len(seen))
	for r := range seen {
		repos = append(repos, r)
	}
	sort.Strings(repos)

	s.WriteString("## Sources\n\n")
	for _, r := range repos {
		fmt.Fprintf(&s, "- `%s` at commit `%s`, licensed %s.\n", r, commits[r], seen[r].License)
	}
	s.WriteString("\nThe text is reproduced verbatim under those licenses. ")
	s.WriteString("Hugo frontmatter and shortcodes are stripped, `{{% include %}}` partials are inlined, ")
	s.WriteString("and root-relative links are rewritten to absolute `docs.docker.com` URLs. ")
	s.WriteString("Nothing else is altered.\n")
	return s.String()
}
