package main

import (
	"sort"
	"strings"
	"text/template"
	"time"
)

const noticeFile = "NOTICE.md"

// The template is a quoted string, not a raw one: it carries markdown code
// spans, and a backtick cannot appear inside a Go raw string literal.
var noticeTemplate = template.Must(template.New("notice").Parse(
	"# Vendored reference\n\n" +
		"Generated by `go run ./tools/vendor-docker-docs`. Do not edit these files by\n" +
		"hand -- a regenerate overwrites them.\n\n" +
		"Last regenerated {{ .Date }}.\n\n" +
		"## Sources\n\n" +
		"{{ range .Sources }}- `{{ .Repo }}` at commit `{{ .Commit }}`, licensed {{ .License }}.\n" +
		"{{ end }}\n" +
		"The text is reproduced verbatim under those licenses. Hugo frontmatter and\n" +
		"shortcodes are stripped, include partials are inlined, and root-relative links\n" +
		"are rewritten to absolute `docs.docker.com` URLs. Nothing else is altered.\n"))

type noticeSource struct {
	Repo    string
	Commit  string
	License string
}

// notice renders the provenance file that sits beside a skill's vendored
// reference, naming every upstream commit the directory was built from.
func notice(b bundle, commits map[string]string) (string, error) {
	byRepo := map[string]upstream{}
	for _, p := range b.Pages {
		byRepo[p.Src.Repo] = p.Src
	}

	sources := make([]noticeSource, 0, len(byRepo))
	for repo, u := range byRepo {
		sources = append(sources, noticeSource{Repo: repo, Commit: commits[repo], License: u.License})
	}
	sort.Slice(sources, func(i, j int) bool { return sources[i].Repo < sources[j].Repo })

	var out strings.Builder
	err := noticeTemplate.Execute(&out, struct {
		Date    string
		Sources []noticeSource
	}{
		Date:    time.Now().UTC().Format("2006-01-02"),
		Sources: sources,
	})
	return out.String(), err
}
